{
  "name": "deepchem_env",
  "channels": [
    "defaults"
  ],
  "dependencies": [
    "python=3.9",
    "pip",
    {
      "pip": [
        "deepchem==2.8.0",
        "rdkit==2025.9.2",
        "tensorflow==2.20.0",
        "scikit-learn==1.6.1",
        "pandas==2.3.3",
        "numpy==2.0.2",
        "matplotlib==3.9.4",
        "jupyter==1.1.1",
        "jupyterlab==4.5.3",
        "scipy==1.13.1"
      ]
    }
  ]
}
